services:
  jupyter:
    build: .
    container_name: taka-jupyter-compose
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      # Ühendab sinu praeguse arvutikausta konteineri /workspace kaustaga
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
